import type { Metadata } from "next";
import {  Ubuntu_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";



const ububu = Ubuntu_Sans({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ububu.className} bg-[#171a1d] text-white`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
